var CARD_GAME_CMD = {};

CARD_GAME_CMD.CMDLOGIN = 1;
CARD_GAME_CMD.CMDNOTIFYDISCONNECT = 37;
CARD_GAME_CMD.CMDPINGPONG = 50;
CARD_GAME_CMD.CMDJOINROOM = 3001;
CARD_GAME_CMD.CMDRECONNECTGAMEROOM = 3002;
CARD_GAME_CMD.CMDJOINROOMFAIL = 3004;

CARD_GAME_CMD.CMDHOLD = 3116;
CARD_GAME_CMD.MONEYBETCONFIG = 3003;
CARD_GAME_CMD.GETLISTROOM = 3014;
CARD_GAME_CMD.TOPSERVER = 1001;
CARD_GAME_CMD.CHEATCARD = 3115;
CARD_GAME_CMD.CMDPINGTEST = 1050;

CARD_GAME_CMD.CHAT_ROOM = 3008;
CARD_GAME_CMD.NO_HU_VANG = 3007;
CARD_GAME_CMD.THONG_TIN_HU_VANG = 3009;
CARD_GAME_CMD.REQUEST_INFO_MOI_CHOI = 3010;
CARD_GAME_CMD.MOI_CHOI = 3011;
CARD_GAME_CMD.ACCEPT_MOI_CHOI = 3012;

CARD_GAME_CMD.CREATEROOM = 3013;
CARD_GAME_CMD.JOIN_GAME_ROOM_BY_ID = 3015;
CARD_GAME_CMD.FIND_ROOM_LOBBY = 3016;
CARD_GAME_CMD.GET_XOCDIA_CONFIG = 3017;
CARD_GAME_CMD.CREATE_ROOM_FAIL = 3018;
